### PR TITLE
Adding url_q/1, url_q/2, url_q/3 to generate the router url with localized route verification

### PR DESCRIPTION
**Pull request by rigzad**
url_q/1, url_q/2, url_q/3 to allow full URL rendering, similar to url(~p"/my_path") but for localized routes.

NB: url(~q"/my_path") would be ideal but conflicts with exisiting url/1 clauses in Phoenix.VerifiedRoutes

### CODE REVIEW

**Comment by kipcole9** [comment]
Thanks very much for the PR. Yes, being able to plug into `Phoenix.VerifiedRoutes.url/1` would be ideal. In face I thought that should work so at minimum I need to add some test cases. I'll review and test this weekend.

Really appreciate the support!

**Comment by kipcole9** [comment]
Not forgotten!

I'm working on a PR that will enable `url/1` to be valid with `sigil_q`. It's a bit of a complicated effort but I think I've found a path forward. Sorry for the delay in getting this done.

**Comment by kipcole9** [comment]
I've pushed a commit to the main branch that adds support for `url/{1,2,3}` when using localised verified routes. Would you consider configuring from GitHub and giving this a test drive? If/when you're ok I'll publish a new release.

Thanks very much for your support and PR, it makes a big difference.

**Comment by rigzad** [comment]
> I've pushed a commit to the main branch that adds support for `url/{1,2,3}` when using localised verified routes. Would you consider configuring from GitHub and giving this a test drive? If/when you're ok I'll publish a new release.

It works for me, thanks !

**Comment by kipcole9** [comment]
I've published [ex_cldr_routes version 1.3.0](https://hex.pm/packages/ex_cldr_routes/1.3.0).

**Pull request closed without merging**
